version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=baha
      - MYSQL_DATABASE=Achat_Db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  My-App:
    depends_on:
      - mysqldb
    image: bahamestiri/achatdevops:1.0
    restart: "no"
    ports:
      - 8082:8082 
    environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/Achat_Db?createDatabaseIfNotExist=true
          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=baha
          - SPRING_JPA_HIBERNATE_DDL_AUTO=update


    stdin_open: true
    tty: true

volumes:
  db:
