version: "3.8"


services: 
	mysqldb:
		image: mysql:5.7
		restart: unless-stopped
		environment:
			- MYSQL_ROOT_PASSWORD=
			- MYSQL_DATABASE=Achat_Db
		ports:
			- 3306:3306
		volumes:
			- db:/var/lib/mysql
	My-App:
		depends_on:
			- mysqldb
		image: bahamestiri/achatdevops:1.0
		restart: on-failure
		ports:
			- 8082:8082
		environment:
			SPRING_APPLICATION_JSON: '{
				"spring.datasource.url" :	"jdbc:mysql://mysql:3306/Achat_Db?createDatabaseIfNotExist=true",
				"spring.datasource.username" : "root",
				"spring.datasource.password" : null,
				"spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MYSQL5InnoDBDialect",
                "spring.jpa.hibernate.ddl-auto" : "Update"
            }'
        stdin_open: true
        tty: true 
    
    volumes:
        db  :
    
		